services:

  subscriptions_db:
    image: postgres:14.6-alpine
    container_name: subscriptions_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      - POSTGRES_DB=subscriptions_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  link-shortener:
    image: subscriptions
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432//subscriptions_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"

  depends_on:
    - subscriptions_db

  volumes:
    postgres_data:
      driver: local