
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(64) UNIQUE NOT NULL CHECK (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
    password TEXT UNIQUE NOT NULL CHECK (length(password) >= 8),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL ,
    start_date DATE,
    end_date DATE,
    is_expired BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0
 );

CREATE INDEX idx_subscriptions_name ON subscriptions(name);
CREATE INDEX idx_subscription_dates ON subscriptions(start_date, end_date);
CREATE INDEX idx_subscription_status ON subscriptions(is_expired);

 CREATE TABLE IF NOT EXISTS user_subscriptions (

     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     user_id               BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
     subscription_id       BIGINT NOT NULL REFERENCES subscriptions(id) ON DELETE RESTRICT,
     is_declined BOOLEAN NOT NULL DEFAULT FALSE,
     activation_date DATE NOT NULL DEFAULT CURRENT_DATE,

     CONSTRAINT uq_user_subscription UNIQUE (user_id, subscription_id)
);

CREATE INDEX idx_user_subs_user ON user_subscriptions(user_id);
CREATE INDEX idx_user_subs_subscription ON user_subscriptions(subscription_id);